const header=document.querySelector('.header'),menu=document.querySelector('.menu'),nav=document.querySelector('.header nav');
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>24),{passive:true});
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false')}));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));

const states=[['CONNECTED','Hello, can I move my Tuesday appointment?','Certainly. I will check what else is free.'],['LISTENING','Thursday afternoon would be ideal.','One moment; I am checking the diary.'],['SORTING IT','Half two works for me.','Lovely. I will move that now.'],['UPDATING SYSTEMS','Will I get a confirmation?','Yes; it is on its way by text.'],['JOB DONE','Brilliant, cheers.','All sorted. Enjoy the rest of your day.']];
let stateIndex=0,seconds=4;const stateEl=document.querySelector('#call-state'),customerEl=document.querySelector('#customer-line'),rev3El=document.querySelector('#rev3-line'),timeEl=document.querySelector('#call-time'),track=[...document.querySelectorAll('.state-track i')],feed=[...document.querySelectorAll('.actions-feed span')];
function advanceCall(){stateIndex=(stateIndex+1)%states.length;const s=states[stateIndex];stateEl.textContent=s[0];customerEl.textContent=s[1];rev3El.textContent=s[2];track.forEach((x,i)=>x.classList.toggle('active',i===stateIndex));feed.forEach((x,i)=>x.classList.toggle('done',i<=stateIndex));if(stateIndex===0)seconds=4}
setInterval(()=>{seconds++;timeEl.textContent=`00:${String(seconds).padStart(2,'0')}`;if(seconds%4===0)advanceCall()},1000);

const liveBoard=document.querySelector('.live-agent-board');
if(liveBoard){const speech=[...liveBoard.querySelectorAll('[data-live-step]')],work=[...liveBoard.querySelectorAll('[data-work-step]')],liveClock=liveBoard.querySelector('#live-clock'),liveStatus=liveBoard.querySelector('#live-status'),liveBadge=liveBoard.querySelector('#live-result-badge'),reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let liveTimers=[],liveRunning=false;const clearLiveTimers=()=>{liveTimers.forEach(clearTimeout);liveTimers=[]};const showLiveStep=step=>{speech.forEach((item,index)=>{item.classList.toggle('live-visible',index<=step);item.classList.toggle('live-current',index===step)});work.forEach(item=>item.classList.toggle('live-done',Number(item.dataset.workStep)<=step));const status=['LISTENING','CHECKING FREE TIMES','SAVING THE BOOKING','SENDING CONFIRMATION'][step];liveStatus.textContent=status;liveClock.textContent=`21:00:${String(4+step*7).padStart(2,'0')}`;const complete=step===3;liveBadge.textContent=complete?'JOB DONE':'CALL LIVE';liveBadge.classList.toggle('complete',complete)};const playLive=()=>{if(liveRunning)return;liveRunning=true;clearLiveTimers();speech.forEach(item=>item.classList.remove('live-visible','live-current'));work.forEach(item=>item.classList.remove('live-done'));[0,1,2,3].forEach((step,index)=>liveTimers.push(setTimeout(()=>showLiveStep(step),350+index*2100)));liveTimers.push(setTimeout(()=>{liveRunning=false;playLive()},10500))};if(reduced)showLiveStep(3);else{const liveObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)playLive();else{clearLiveTimers();liveRunning=false}}),{threshold:.25});liveObserver.observe(liveBoard)}}

const industries=[['Private Clinics','Rev3 answers patient questions, books consultations and organises callbacks. Every caller gets a clear next step, even after the clinic closes.',['New patient','Useful answers','Diary checked','Sorted']],['Property','Qualifies buyers and tenants, captures the wish list and gets the viewing in the diary before the good one goes.',['What they fancy','Buyer or tenant','Viewing found','Keys ready']],['Home Services and Trades','Gets the job details, postcode and urgency straight; even when you are up a ladder and cannot answer.',['What is broken','Whereabouts','How urgent','Visit booked']],['Automotive','Books services, handles dealership questions and captures leads without putting anyone in the slow lane.',['Reg details','What it needs','Garage diary','Booked in']],['Professional Services','Asks the right first questions, captures a tidy brief and books the consultation with the right person.',['What is needed','Good questions','Right expert','Meeting booked']]];
const industrySelector=document.querySelector('.industry-selector'),industryButtons=[...industrySelector.querySelectorAll('button')],industryPanel=document.querySelector('.industry-demo');
const selectIndustry=(button,{scroll=false}={})=>{industryButtons.forEach(x=>{const active=x===button;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active));x.tabIndex=active?0:-1});const d=industries[Number(button.dataset.industry)];document.querySelector('#industry-title').textContent=d[0];document.querySelector('#industry-copy').textContent=d[1];document.querySelector('#industry-chips').innerHTML=d[2].map(x=>`<span>${x}</span>`).join('');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)industryPanel.animate([{opacity:.55},{opacity:1}],{duration:240,easing:'ease-out'});if(scroll&&matchMedia('(max-width:650px)').matches)industrySelector.scrollTo({left:button.offsetLeft,behavior:'smooth'})};
industryButtons.forEach(button=>button.addEventListener('click',()=>selectIndustry(button,{scroll:true})));

const enableSwipeSelection=(container,buttons,select)=>{const progress=document.createElement('div');progress.className='swipe-progress';progress.innerHTML='<i></i>';container.after(progress);let timer;const supportsScrollEnd='onscrollend' in window;const nearest=()=>buttons.reduce((best,button)=>{const distance=Math.abs(button.offsetLeft-container.scrollLeft);return distance<best.distance?{button,distance}:best},{button:buttons[0],distance:Infinity}).button;const settle=()=>select(nearest());container.addEventListener('scroll',()=>{if(!matchMedia('(max-width:650px)').matches)return;const max=container.scrollWidth-container.clientWidth;progress.querySelector('i').style.transform=`scaleX(${max?container.scrollLeft/max:0})`;if(!supportsScrollEnd){clearTimeout(timer);timer=setTimeout(settle,180)}},{passive:true});if(supportsScrollEnd)container.addEventListener('scrollend',settle)};

enableSwipeSelection(industrySelector,industryButtons,selectIndustry);
selectIndustry(industryButtons[0]);



const enquiryModal=document.querySelector("#enquiry-modal"),enquiryForm=document.querySelector("#enquiry-form"),enquiryTitle=document.querySelector("#enquiry-title"),enquiryIntro=enquiryModal.querySelector(".enquiry-card>p:not(.eyebrow)"),enquiryPrompt=enquiryForm.querySelector("textarea");document.querySelectorAll("[data-open-enquiry]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();const inPerson=a.dataset.meeting==="in-person";enquiryTitle.textContent=inPerson?"Book an in-person meeting":"See Rev3 on a real call";enquiryIntro.textContent=inPerson?"Tell us when you would like to visit our London office and what you want your voice agent to handle.":"Tell us where the phone work piles up. We will show you how a Rev3 voice agent can handle it.";enquiryPrompt.placeholder=inPerson?"Preferred dates and what you would like to discuss":"For example, after-hours enquiries and appointment bookings";enquiryModal.hidden=false;document.body.style.overflow="hidden";setTimeout(()=>enquiryModal.querySelector("input").focus(),0)}));document.querySelectorAll("[data-close-enquiry]").forEach(b=>b.addEventListener("click",()=>{enquiryModal.hidden=true;document.body.style.overflow=""}));addEventListener("keydown",e=>{if(e.key==="Escape"&&!enquiryModal.hidden){enquiryModal.hidden=true;document.body.style.overflow=""}});enquiryForm.addEventListener("submit",async e=>{e.preventDefault();const button=enquiryForm.querySelector("button[type=submit]"),status=enquiryForm.querySelector(".form-status"),payload=Object.fromEntries(new FormData(enquiryForm));button.disabled=true;button.textContent="Sending";status.textContent="";try{const response=await fetch("/api/enquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to send");enquiryForm.reset();status.textContent="Thank you. Your enquiry has been sent.";button.textContent="Sent"}catch(error){status.textContent="We could not send your enquiry. Please email info@rev3.uk.";button.textContent="Try Again"}finally{button.disabled=false}});

const typedLines=[...document.querySelectorAll("[data-type-text]")];const typeConversation=async()=>{for(const line of typedLines){const text=line.dataset.typeText;line.textContent="";line.classList.add("typing");for(const char of text){line.textContent+=char;await new Promise(resolve=>setTimeout(resolve,24))}line.classList.remove("typing");await new Promise(resolve=>setTimeout(resolve,300))}};const conversationPanel=document.querySelector(".split-screen");if(conversationPanel&&typedLines.length){const typingObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){typingObserver.disconnect();if(matchMedia("(prefers-reduced-motion: reduce)").matches)typedLines.forEach(line=>line.textContent=line.dataset.typeText);else typeConversation()}}),{threshold:.35});typingObserver.observe(conversationPanel)}
