const header=document.querySelector('.header'),menu=document.querySelector('.menu'),nav=document.querySelector('.header nav');
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>24),{passive:true});
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false')}));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));

const states=[['CONNECTED','Hello — can I move my Tuesday appointment?','Certainly. I will check what else is free.'],['LISTENING','Thursday afternoon would be ideal.','One moment — I am checking the diary.'],['SORTING IT','Half two works for me.','Lovely. I will move that now.'],['UPDATING SYSTEMS','Will I get a confirmation?','Yes — it is on its way by text.'],['JOB DONE','Brilliant, cheers.','All sorted. Enjoy the rest of your day.']];
let stateIndex=0,seconds=4;const stateEl=document.querySelector('#call-state'),customerEl=document.querySelector('#customer-line'),rev3El=document.querySelector('#rev3-line'),timeEl=document.querySelector('#call-time'),track=[...document.querySelectorAll('.state-track i')],feed=[...document.querySelectorAll('.actions-feed span')];
function advanceCall(){stateIndex=(stateIndex+1)%states.length;const s=states[stateIndex];stateEl.textContent=s[0];customerEl.textContent=s[1];rev3El.textContent=s[2];track.forEach((x,i)=>x.classList.toggle('active',i===stateIndex));feed.forEach((x,i)=>x.classList.toggle('done',i<=stateIndex));if(stateIndex===0)seconds=4}
setInterval(()=>{seconds++;timeEl.textContent=`00:${String(seconds).padStart(2,'0')}`;if(seconds%4===0)advanceCall()},1000);

const problemData={missed:['RECEPTION DESK · ON SHIFT','Answers every call in your tone, works out what is needed and keeps the queue moving — including evenings and busy spells.','Meet your unflappable receptionist.','Handles FAQs, messages, routing, rescheduling and urgent-call rules. No hold-music marathon. No mystery voicemail.'],repeat:['OPERATIONS DESK · GETTING IT DONE','Takes the repeatable phone admin off everyone’s plate, then writes the result back to the right system.','A coordinator who actually loves admin.','Checks diaries, creates or changes bookings, sends confirmations, captures details and updates your CRM while the caller is still on the line.'],convert:['ENQUIRY DESK · QUALIFYING','Asks the useful questions, spots genuine intent and makes sure promising enquiries leave with a clear next step.','Your sharpest first conversation.','Qualifies leads against your rules, answers approved questions, books the next meeting and hands hot or complex enquiries to a human with context.']};
const problemTabs=document.querySelector('.problem-tabs'),problemButtons=[...problemTabs.querySelectorAll('button')],problemPanel=document.querySelector('.problem-panel');
const selectProblem=(button,{scroll=false}={})=>{problemButtons.forEach(x=>{const active=x===button;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active));x.tabIndex=active?0:-1});const d=problemData[button.dataset.problem];document.querySelector('#problem-status').textContent=d[0];document.querySelector('#problem-pain').textContent=d[1];document.querySelector('#problem-outcome').textContent=d[2];document.querySelector('#problem-detail').textContent=d[3];if(!matchMedia('(prefers-reduced-motion: reduce)').matches)problemPanel.animate([{opacity:.55},{opacity:1}],{duration:240,easing:'ease-out'});if(scroll&&matchMedia('(max-width:650px)').matches)problemTabs.scrollTo({left:button.offsetLeft,behavior:'smooth'})};
problemButtons.forEach(button=>button.addEventListener('click',()=>selectProblem(button,{scroll:true})));

const industries=[['Private Clinics','Your digital receptionist handles patient questions, books consultations and organises callbacks — calmly, even on a Monday morning.',['New patient','Useful answers','Diary checked','Sorted']],['Property','Qualifies buyers and tenants, captures the wish list and gets the viewing in the diary before the good one goes.',['What they fancy','Buyer or tenant','Viewing found','Keys ready']],['Home Services and Trades','Gets the job details, postcode and urgency straight — even when you are up a ladder and cannot answer.',['What is broken','Whereabouts','How urgent','Visit booked']],['Automotive','Books services, handles dealership questions and captures leads without putting anyone in the slow lane.',['Reg details','What it needs','Garage diary','Booked in']],['Professional Services','Asks the right first questions, captures a tidy brief and books the consultation with the right person.',['What is needed','Good questions','Right expert','Meeting booked']]];
const industrySelector=document.querySelector('.industry-selector'),industryButtons=[...industrySelector.querySelectorAll('button')],industryPanel=document.querySelector('.industry-demo');
const selectIndustry=(button,{scroll=false}={})=>{industryButtons.forEach(x=>{const active=x===button;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active));x.tabIndex=active?0:-1});const d=industries[Number(button.dataset.industry)];document.querySelector('#industry-title').textContent=d[0];document.querySelector('#industry-copy').textContent=d[1];document.querySelector('#industry-chips').innerHTML=d[2].map(x=>`<span>${x}</span>`).join('');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)industryPanel.animate([{opacity:.55},{opacity:1}],{duration:240,easing:'ease-out'});if(scroll&&matchMedia('(max-width:650px)').matches)industrySelector.scrollTo({left:button.offsetLeft,behavior:'smooth'})};
industryButtons.forEach(button=>button.addEventListener('click',()=>selectIndustry(button,{scroll:true})));

const enableSwipeSelection=(container,buttons,select)=>{const progress=document.createElement('div');progress.className='swipe-progress';progress.innerHTML='<i></i>';container.after(progress);let timer;const supportsScrollEnd='onscrollend' in window;const nearest=()=>buttons.reduce((best,button)=>{const distance=Math.abs(button.offsetLeft-container.scrollLeft);return distance<best.distance?{button,distance}:best},{button:buttons[0],distance:Infinity}).button;const settle=()=>select(nearest());container.addEventListener('scroll',()=>{if(!matchMedia('(max-width:650px)').matches)return;const max=container.scrollWidth-container.clientWidth;progress.querySelector('i').style.transform=`scaleX(${max?container.scrollLeft/max:0})`;if(!supportsScrollEnd){clearTimeout(timer);timer=setTimeout(settle,180)}},{passive:true});if(supportsScrollEnd)container.addEventListener('scrollend',settle)};
enableSwipeSelection(problemTabs,problemButtons,selectProblem);
enableSwipeSelection(industrySelector,industryButtons,selectIndustry);
selectProblem(problemButtons[0]);selectIndustry(industryButtons[0]);



const enquiryModal=document.querySelector("#enquiry-modal"),enquiryForm=document.querySelector("#enquiry-form");document.querySelectorAll("[data-open-enquiry]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();enquiryModal.hidden=false;document.body.style.overflow="hidden";setTimeout(()=>enquiryModal.querySelector("input").focus(),0)}));document.querySelectorAll("[data-close-enquiry]").forEach(b=>b.addEventListener("click",()=>{enquiryModal.hidden=true;document.body.style.overflow=""}));addEventListener("keydown",e=>{if(e.key==="Escape"&&!enquiryModal.hidden){enquiryModal.hidden=true;document.body.style.overflow=""}});enquiryForm.addEventListener("submit",async e=>{e.preventDefault();const button=enquiryForm.querySelector("button[type=submit]"),status=enquiryForm.querySelector(".form-status"),payload=Object.fromEntries(new FormData(enquiryForm));button.disabled=true;button.textContent="Sending";status.textContent="";try{const response=await fetch("/api/enquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to send");enquiryForm.reset();status.textContent="Thank you. Your enquiry has been sent.";button.textContent="Sent"}catch(error){status.textContent="We could not send your enquiry. Please email info@rev3.uk.";button.textContent="Try Again"}finally{button.disabled=false}});

const typedLines=[...document.querySelectorAll("[data-type-text]")];const typeConversation=async()=>{for(const line of typedLines){const text=line.dataset.typeText;line.textContent="";line.classList.add("typing");for(const char of text){line.textContent+=char;await new Promise(resolve=>setTimeout(resolve,24))}line.classList.remove("typing");await new Promise(resolve=>setTimeout(resolve,300))}};const conversationPanel=document.querySelector(".split-screen");if(conversationPanel&&typedLines.length){const typingObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){typingObserver.disconnect();if(matchMedia("(prefers-reduced-motion: reduce)").matches)typedLines.forEach(line=>line.textContent=line.dataset.typeText);else typeConversation()}}),{threshold:.35});typingObserver.observe(conversationPanel)}
