const header=document.querySelector('.header'),menu=document.querySelector('.menu'),nav=document.querySelector('.header nav');
addEventListener('scroll',()=>header.classList.toggle('scrolled',scrollY>24),{passive:true});
menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');document.body.classList.remove('menu-open');menu.setAttribute('aria-expanded','false')}));
const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');reveal.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));

const states=[['CONNECTED','I would like to book a consultation.','Of course. Is this your first appointment?'],['LISTENING','Yes, this is my first visit.','Thank you. Which day works best for you?'],['QUALIFYING','Thursday afternoon.','I will check the approved availability.'],['CHECKING CALENDAR','Thursday afternoon would work.','I have 2:30pm available. Shall I book it?'],['BOOKED','Yes, please.','You are booked for Thursday at 2:30pm.']];
let stateIndex=0,seconds=4;const stateEl=document.querySelector('#call-state'),customerEl=document.querySelector('#customer-line'),rev3El=document.querySelector('#rev3-line'),timeEl=document.querySelector('#call-time'),track=[...document.querySelectorAll('.state-track i')],feed=[...document.querySelectorAll('.actions-feed span')];
function advanceCall(){stateIndex=(stateIndex+1)%states.length;const s=states[stateIndex];stateEl.textContent=s[0];customerEl.textContent=s[1];rev3El.textContent=s[2];track.forEach((x,i)=>x.classList.toggle('active',i===stateIndex));feed.forEach((x,i)=>x.classList.toggle('done',i<=stateIndex));if(stateIndex===0)seconds=4}
setInterval(()=>{seconds++;timeEl.textContent=`00:${String(seconds).padStart(2,'0')}`;if(seconds%4===0)advanceCall()},1000);

const problemData={missed:['INCOMING CALL','Calls often arrive while your team is busy or after hours. When nobody answers, the opportunity can disappear.','Capture every valuable enquiry.','Rev3 can cover overflow and after-hours calls, capture the enquiry and move it toward an approved next step.'],repeat:['ROUTINE REQUEST','Your team spends hours answering the same questions and collecting the same details.','Let Rev3 complete routine requests.','Opening hours, availability, approved FAQs, information capture and rescheduling can follow a clear workflow.'],convert:['INTENT DETECTED','Someone answers, but the caller never reaches a booking or meaningful next step.','Turn intent into action.','Rev3 qualifies the enquiry, checks availability, completes the approved booking and updates the CRM.']};
document.querySelectorAll('.problem-tabs button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.problem-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=problemData[b.dataset.problem];document.querySelector('#problem-status').textContent=d[0];document.querySelector('#problem-pain').textContent=d[1];document.querySelector('#problem-outcome').textContent=d[2];document.querySelector('#problem-detail').textContent=d[3]}));

const industries=[['Private Clinics','Handle new patient enquiries, approved FAQs, consultation booking and callbacks.',['New enquiry','Approved questions','Availability','Booked']],['Property','Qualify property enquiries, capture requirements and book viewings.',['Property intent','Buyer or tenant','Viewing slots','Booked']],['Home Services and Trades','Capture job details, location and urgency according to business rules.',['Job type','Location','Priority rules','Visit booked']],['Automotive','Handle service booking, dealership enquiries and lead capture.',['Vehicle details','Service needed','Availability','Booking']],['Professional Services','Qualify inbound leads, capture information and schedule consultations.',['Enquiry type','Approved questions','Consultation','CRM update']]];
document.querySelectorAll('.industry-selector button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.industry-selector button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const d=industries[Number(b.dataset.industry)];document.querySelector('#industry-title').textContent=d[0];document.querySelector('#industry-copy').textContent=d[1];document.querySelector('#industry-chips').innerHTML=d[2].map(x=>`<span>${x}</span>`).join('')}));



const enquiryModal=document.querySelector("#enquiry-modal"),enquiryForm=document.querySelector("#enquiry-form");document.querySelectorAll("[data-open-enquiry]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();enquiryModal.hidden=false;document.body.style.overflow="hidden";setTimeout(()=>enquiryModal.querySelector("input").focus(),0)}));document.querySelectorAll("[data-close-enquiry]").forEach(b=>b.addEventListener("click",()=>{enquiryModal.hidden=true;document.body.style.overflow=""}));addEventListener("keydown",e=>{if(e.key==="Escape"&&!enquiryModal.hidden){enquiryModal.hidden=true;document.body.style.overflow=""}});enquiryForm.addEventListener("submit",async e=>{e.preventDefault();const button=enquiryForm.querySelector("button[type=submit]"),status=enquiryForm.querySelector(".form-status"),payload=Object.fromEntries(new FormData(enquiryForm));button.disabled=true;button.textContent="Sending";status.textContent="";try{const response=await fetch("/api/enquiry",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"Unable to send");enquiryForm.reset();status.textContent="Thank you. Your enquiry has been sent.";button.textContent="Sent"}catch(error){status.textContent="We could not send your enquiry. Please email rev3ltd@gmail.com.";button.textContent="Try Again"}finally{button.disabled=false}});

const typedLines=[...document.querySelectorAll("[data-type-text]")];const typeConversation=async()=>{for(const line of typedLines){const text=line.dataset.typeText;line.textContent="";line.classList.add("typing");for(const char of text){line.textContent+=char;await new Promise(resolve=>setTimeout(resolve,24))}line.classList.remove("typing");await new Promise(resolve=>setTimeout(resolve,300))}};const conversationPanel=document.querySelector(".split-screen");if(conversationPanel&&typedLines.length){const typingObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){typingObserver.disconnect();if(matchMedia("(prefers-reduced-motion: reduce)").matches)typedLines.forEach(line=>line.textContent=line.dataset.typeText);else typeConversation()}}),{threshold:.35});typingObserver.observe(conversationPanel)}
